apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 500113026115.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googleclothes:2e54550c3f9b42440b8700f4bc645d262cd2bc61
        ports:
        - containerPort: 80
