apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 500113026115.dkr.ecr.us-west-2.amazonaws.com/shopping-site-electronics:807aef2c2c7296146f2f3ecd26bc923b3de34f2f
        ports:
        - containerPort: 80
