apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 500113026115.dkr.ecr.us-west-2.amazonaws.com/shopping-site-main:2e54550c3f9b42440b8700f4bc645d262cd2bc61
        ports:
        - containerPort: 80

