apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 500113026115.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlemusic:2e54550c3f9b42440b8700f4bc645d262cd2bc61
        ports:
        - containerPort: 80
